/**
 * Spring Boot REST API
 * \"Spring Boot REST API for the College Schedule Web App\"
 *
 * OpenAPI spec version: 0.1
 * Contact: sedoff@zohomail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CoursewebcontrollerApi
 */
public class CoursewebcontrollerApiTest {

    private final CoursewebcontrollerApi api = new CoursewebcontrollerApi();

    
    /**
     * createCourse
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCourseUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer professorId = null;
        // String response = api.createCourseUsingPOST(description, id, mode, name, professorId);

        // TODO: test validations
    }
    
    /**
     * deleteCourse
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCourseUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer professorId = null;
        // String response = api.deleteCourseUsingPOST(description, id, mode, name, professorId);

        // TODO: test validations
    }
    
    /**
     * gedItParam
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gedItParamUsingGETTest() throws ApiException {
        String id = null;
        String description = null;
        String mode = null;
        String name = null;
        Integer professorId = null;
        // String response = api.gedItParamUsingGET(id, description, mode, name, professorId);

        // TODO: test validations
    }
    
    /**
     * getCourses
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCoursesUsingGETTest() throws ApiException {
        // String response = api.getCoursesUsingGET();

        // TODO: test validations
    }
    
    /**
     * updateCourse
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCourseUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer professorId = null;
        // String response = api.updateCourseUsingPOST(description, id, mode, name, professorId);

        // TODO: test validations
    }
    
}
