/**
 * Spring Boot REST API
 * \"Spring Boot REST API for the College Schedule Web App\"
 *
 * OpenAPI spec version: 0.1
 * Contact: sedoff@zohomail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupwebcontrollerApi
 */
public class GroupwebcontrollerApiTest {

    private final GroupwebcontrollerApi api = new GroupwebcontrollerApi();

    
    /**
     * createGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        // String response = api.createGroupUsingPOST(description, id, mode, name);

        // TODO: test validations
    }
    
    /**
     * deleteGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        // String response = api.deleteGroupUsingPOST(description, id, mode, name);

        // TODO: test validations
    }
    
    /**
     * gedItParam
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void gedItParamUsingGET1Test() throws ApiException {
        String id = null;
        String description = null;
        String mode = null;
        String name = null;
        // String response = api.gedItParamUsingGET1(id, description, mode, name);

        // TODO: test validations
    }
    
    /**
     * getGroups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsUsingGETTest() throws ApiException {
        // String response = api.getGroupsUsingGET();

        // TODO: test validations
    }
    
    /**
     * updateGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGroupUsingPOSTTest() throws ApiException {
        String description = null;
        Integer id = null;
        String mode = null;
        String name = null;
        // String response = api.updateGroupUsingPOST(description, id, mode, name);

        // TODO: test validations
    }
    
}
