/**
 * Spring Boot REST API
 * \"Spring Boot REST API for the College Schedule Web App\"
 *
 * OpenAPI spec version: 0.1
 * Contact: sedoff@zohomail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LessonwebcontrollerApi
 */
public class LessonwebcontrollerApiTest {

    private final LessonwebcontrollerApi api = new LessonwebcontrollerApi();

    
    /**
     * createLesson
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createLessonUsingPOSTTest() throws ApiException {
        String endTime = null;
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        Integer professorId = null;
        String startTime = null;
        // String response = api.createLessonUsingPOST(endTime, groupId, id, mode, professorId, startTime);

        // TODO: test validations
    }
    
    /**
     * deleteLesson
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteLessonUsingPOSTTest() throws ApiException {
        String endTime = null;
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        Integer professorId = null;
        String startTime = null;
        // String response = api.deleteLessonUsingPOST(endTime, groupId, id, mode, professorId, startTime);

        // TODO: test validations
    }
    
    /**
     * getIdParam
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIdParamUsingGETTest() throws ApiException {
        String id = null;
        String endTime = null;
        Integer groupId = null;
        String mode = null;
        Integer professorId = null;
        String startTime = null;
        // String response = api.getIdParamUsingGET(id, endTime, groupId, mode, professorId, startTime);

        // TODO: test validations
    }
    
    /**
     * getLessons
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLessonsUsingGETTest() throws ApiException {
        // String response = api.getLessonsUsingGET();

        // TODO: test validations
    }
    
    /**
     * updateLesson
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateLessonUsingPOSTTest() throws ApiException {
        String endTime = null;
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        Integer professorId = null;
        String startTime = null;
        // String response = api.updateLessonUsingPOST(endTime, groupId, id, mode, professorId, startTime);

        // TODO: test validations
    }
    
}
