/**
 * Spring Boot REST API
 * \"Spring Boot REST API for the College Schedule Web App\"
 *
 * OpenAPI spec version: 0.1
 * Contact: sedoff@zohomail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StudentwebcontrollerApi
 */
public class StudentwebcontrollerApiTest {

    private final StudentwebcontrollerApi api = new StudentwebcontrollerApi();

    
    /**
     * createStudent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createStudentUsingPOSTTest() throws ApiException {
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer schoolYear = null;
        // String response = api.createStudentUsingPOST(groupId, id, mode, name, schoolYear);

        // TODO: test validations
    }
    
    /**
     * deleteStudent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStudentUsingPOSTTest() throws ApiException {
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer schoolYear = null;
        // String response = api.deleteStudentUsingPOST(groupId, id, mode, name, schoolYear);

        // TODO: test validations
    }
    
    /**
     * getIdParam
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIdParamUsingGET2Test() throws ApiException {
        String id = null;
        Integer groupId = null;
        String mode = null;
        String name = null;
        Integer schoolYear = null;
        // String response = api.getIdParamUsingGET2(id, groupId, mode, name, schoolYear);

        // TODO: test validations
    }
    
    /**
     * getStudents
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStudentsUsingGETTest() throws ApiException {
        // String response = api.getStudentsUsingGET();

        // TODO: test validations
    }
    
    /**
     * updateStudent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateStudentUsingPOSTTest() throws ApiException {
        Integer groupId = null;
        Integer id = null;
        String mode = null;
        String name = null;
        Integer schoolYear = null;
        // String response = api.updateStudentUsingPOST(groupId, id, mode, name, schoolYear);

        // TODO: test validations
    }
    
}
